import LeanCode.Basic

-- ===== Layer 0 — general math (Group MA) + FMSA polynomial base =====
import LeanCode.Analysis.ArgumentPrinciple
import LeanCode.Analysis.BanachPoleFamily
import LeanCode.Analysis.BoundaryGrowth
import LeanCode.Analysis.ComplexDiskGeometry
import LeanCode.Analysis.ContourDeformation
import LeanCode.Analysis.ContourHomotopy
import LeanCode.Analysis.ContourSumUpperHalfPlane
import LeanCode.Analysis.ConvolutionLeibniz
import LeanCode.Analysis.ExpTaylorLimits
import LeanCode.Analysis.FourierAEInjective
import LeanCode.Analysis.HalfDiskArgumentPrinciple
import LeanCode.Analysis.HomotopyInvariance
import LeanCode.Analysis.IntervalIntegralSwap
import LeanCode.Analysis.JensenCounting
import LeanCode.Analysis.JordanLemma
import LeanCode.Analysis.MatrixFin1
import LeanCode.Analysis.MatrixIdentity
import LeanCode.Analysis.MatrixInverseHolomorphic
import LeanCode.Analysis.MatrixRadialWienerHopf
import LeanCode.Analysis.MatrixWienerHopf
import LeanCode.Analysis.MittagLeffler
import LeanCode.Analysis.PoleSeriesSummable
import LeanCode.Analysis.RadialFourierInversion
import LeanCode.Analysis.RadialWienerHopf
import LeanCode.Analysis.ResidueAtSimplePole
import LeanCode.Analysis.SokhotskiPlemelj
import LeanCode.Analysis.SokhotskiPlemeljLower
import LeanCode.Analysis.Taylor4Calculus
import LeanCode.Analysis.TrigDeriv
import LeanCode.Analysis.VanDerCorput
import LeanCode.Analysis.Volterra
import LeanCode.Analysis.VolterraBanach
import LeanCode.Analysis.WienerHopf
import LeanCode.Analysis.WienerRenewal
import LeanCode.Analysis.ZeroCountHomotopy
import LeanCode.FMSAPoly.ContactValue
import LeanCode.FMSAPoly.EijStructure
import LeanCode.FMSAPoly.ExpBasis
import LeanCode.FMSAPoly.OriginCheck
import LeanCode.FMSAPoly.OriginConstraint
import LeanCode.FMSAPoly.PolyApproxCorollary
import LeanCode.FMSAPoly.PolyApproxFails

-- ===== Layer 1 — single-component hard sphere (PY-HS solution) =====
import LeanCode.HardSphere.BaxterChordFamily
import LeanCode.HardSphere.BaxterFactor
import LeanCode.HardSphere.BaxterOriginTripleZero
import LeanCode.HardSphere.BaxterOzStar
import LeanCode.HardSphere.BaxterPoleFamilyConcrete
import LeanCode.HardSphere.BaxterPoleGuess
import LeanCode.HardSphere.BaxterPoles
import LeanCode.HardSphere.BaxterRealSpace
import LeanCode.HardSphere.BaxterRenewal
import LeanCode.HardSphere.BaxterRenewalDecay
import LeanCode.HardSphere.BaxterResidue
import LeanCode.HardSphere.BaxterWienerHopf
import LeanCode.HardSphere.BaxterWienerHopfComplex
import LeanCode.HardSphere.BaxterZeros
import LeanCode.HardSphere.HExplicitConcrete
import LeanCode.HardSphere.HExplicitRegularity
import LeanCode.HardSphere.JumpAsymptotic
import LeanCode.HardSphere.MatrixN1
import LeanCode.HardSphere.OZExteriorBridge
import LeanCode.HardSphere.OZFourierBridge
import LeanCode.HardSphere.OzCollapseInner
import LeanCode.HardSphere.OzCollapseTwoSigma
import LeanCode.HardSphere.OzExteriorConvIntegrable
import LeanCode.HardSphere.OzExteriorDerivBundle
import LeanCode.HardSphere.OzExteriorIntegrability
import LeanCode.HardSphere.OzExteriorSmooth
import LeanCode.HardSphere.OzFixedPtDilute
import LeanCode.HardSphere.OzFixedPtHExplicit
import LeanCode.HardSphere.OzFixedPtHExplicitFinal
import LeanCode.HardSphere.OzSymbolCoercive
import LeanCode.HardSphere.OzWienerHopfBounded
import LeanCode.HardSphere.PYDCF
import LeanCode.HardSphere.PYOZ
import LeanCode.HardSphere.PYOZ_GHS
import LeanCode.HardSphere.QhatDecomposition
import LeanCode.HardSphere.QhatDeriv
import LeanCode.HardSphere.RadialFourier
import LeanCode.HardSphere.RadialFourierCHS
import LeanCode.HardSphere.RadialFourierCHSComplex
import LeanCode.HardSphere.RadialFourierInjective
import LeanCode.HardSphere.RadialLaplace
import LeanCode.HardSphere.ShellKernel
import LeanCode.HardSphere.SingleCompIdentity
import LeanCode.HardSphere.SingleCompReduction

-- ===== Layer 2 — N-component pure hard-sphere mixture =====
import LeanCode.HSMixture.AppendixWDet
import LeanCode.HSMixture.ArcAmplitudeBound
import LeanCode.HSMixture.CHSFlatInner
import LeanCode.HSMixture.CHSKink
import LeanCode.HSMixture.CHSKinkWB
import LeanCode.HSMixture.MatrixDetPoleFree
import LeanCode.HSMixture.MatrixQ0
import LeanCode.HSMixture.MixtureBaxterSeed
import LeanCode.HSMixture.PhysHSMixRhoWeight
import LeanCode.HSMixture.MixtureChordFamily
import LeanCode.HSMixture.MixtureDetEntire
import LeanCode.HSMixture.MixtureDetEscape
import LeanCode.HSMixture.MixtureDetGeneralN
import LeanCode.HSMixture.MixtureDetHcont
import LeanCode.HSMixture.MixtureDetHomotopy
import LeanCode.HSMixture.MixtureDetHomotopyPhys
import LeanCode.HSMixture.MixtureDetOrigin
import LeanCode.HSMixture.MixtureDetUniform
import LeanCode.HSMixture.MixtureH1Assembly
import LeanCode.HSMixture.MixtureHSCounting
import LeanCode.HSMixture.MixtureHSPoles
import LeanCode.HSMixture.MixtureHSZeros
import LeanCode.HSMixture.MixtureLaurent
import LeanCode.HSMixture.MixtureMLBound
import LeanCode.HSMixture.MixtureNoSpinodal
import LeanCode.HSMixture.MixtureNoSpinodalN1
import LeanCode.HSMixture.MixtureOzStar
import LeanCode.HSMixture.MixtureOzStarIntegrable
import LeanCode.HSMixture.MixtureQ0Inverse
import LeanCode.HSMixture.MixtureRDFUniqueness
import LeanCode.HSMixture.MixtureZerosPhys
import LeanCode.HSMixture.Q0Complex
import LeanCode.HSMixture.Q0ComplexDetMatch
import LeanCode.HSMixture.Q0ComplexDetMatchClose
import LeanCode.HSMixture.Q0ComplexH1Assembly
import LeanCode.HSMixture.Q0ComplexRankTwo
import LeanCode.HSMixture.Q0ComplexRepr
import LeanCode.HSMixture.Q0DetContourOrientation
import LeanCode.HSMixture.Q0OriginFactor
import LeanCode.HSMixture.Q0HermitianAxis
import LeanCode.HSMixture.Q0DetLimit
import LeanCode.HSMixture.Q0DetRankTwo
import LeanCode.HSMixture.Q0MomentGeOne
import LeanCode.HSMixture.WhiteBearFMT
import LeanCode.HSMixture.MixtureCoercivityReduction
import LeanCode.HSMixture.MixtureSymbolBridge
import LeanCode.HSMixture.MatrixGramWienerHopf
import LeanCode.HSMixture.MixtureWienerHopfN1
import LeanCode.HSMixture.MatrixBaxterFourierWH
import LeanCode.HSMixture.MatrixWienerKhinchin

-- ===== Layer 3 — single-component Yukawa OZ (+ generic-scalar base) =====
import LeanCode.YukawaOZ.BijReduction
import LeanCode.YukawaOZ.ContactMatching
import LeanCode.YukawaOZ.I1I2Integrals
import LeanCode.YukawaOZ.InnerOriginBC
import LeanCode.YukawaOZ.MSAClosedForm
import LeanCode.YukawaOZ.MSAElimination
import LeanCode.YukawaOZ.MSABaxterTransform
import LeanCode.YukawaOZ.MSABlumHoyeSystem
import LeanCode.YukawaOZ.OuterDCF
import LeanCode.YukawaOZ.Splitting
import LeanCode.YukawaOZ.YukawaCausalProjection
import LeanCode.YukawaOZ.YukawaInnerCore

-- ===== Layer 4 — N-component Yukawa mixture OZ =====
import LeanCode.YukawaOZMix.AppendixBridgeN1
import LeanCode.YukawaOZMix.InnerDecomp
import LeanCode.YukawaOZMix.MixtureClosedForm
import LeanCode.YukawaOZMix.MixtureConvolution
import LeanCode.YukawaOZMix.MixtureDCFSmooth
import LeanCode.YukawaOZMix.MixtureHSDCF
import LeanCode.YukawaOZMix.MixtureCorrelationDeriv
import LeanCode.YukawaOZMix.MixtureCorrelationDerivUpper
import LeanCode.YukawaOZMix.RadialFourierQFwd
import LeanCode.YukawaOZMix.RadialFourierQFwdOffdiag
import LeanCode.YukawaOZMix.RadialFourierPMix
import LeanCode.YukawaOZMix.MixtureInnerDCF
import LeanCode.YukawaOZMix.MixtureMLSeries
import LeanCode.YukawaOZMix.MixturePolyCoeffs
import LeanCode.YukawaOZMix.MixtureRDFAntideriv
import LeanCode.YukawaOZMix.MixtureRDFContact
import LeanCode.YukawaOZMix.MixtureRDFEqualDiam
import LeanCode.YukawaOZMix.MixtureYukawaTransform
import LeanCode.YukawaOZMix.MixtureYukawaResidue
import LeanCode.YukawaOZMix.MixtureYukawaContourTerm
import LeanCode.YukawaOZMix.YukawaArcBound
import LeanCode.YukawaOZMix.MixtureRDFPoleData
import LeanCode.YukawaOZMix.MixtureRDFStructureFactor
import LeanCode.YukawaOZMix.MixtureRealSpace
import LeanCode.YukawaOZMix.MixtureRowSum
import LeanCode.YukawaOZMix.PhysMixRhoWeightRenewal
import LeanCode.YukawaOZMix.MixtureCorrectedSeed
import LeanCode.YukawaOZMix.ExtendedSeedRhoWeight
import LeanCode.YukawaOZMix.MixturePoleExhaustion
import LeanCode.YukawaOZMix.MixtureDCFAEInjective
import LeanCode.YukawaOZMix.MixtureBaxterODEEqualDiam
import LeanCode.YukawaOZMix.MixtureBaxterODEUnequalDiam
import LeanCode.YukawaOZMix.MixtureBaxterODEUnequalDiamN
import LeanCode.YukawaOZMix.MixtureYukawaBij
import LeanCode.YukawaOZMix.OffDiagDecay
import LeanCode.YukawaOZMix.ReflectedTermSupports
import LeanCode.YukawaOZMix.SpectralAmplitude
import LeanCode.YukawaOZMix.WHSupports
import LeanCode.YukawaOZMix.YukawaCausalResidue
import LeanCode.YukawaOZMix.YukawaPoleResidue
import LeanCode.YukawaOZMix.YukawaWienerHopf

-- ===== Layer 5 — applications (free energy, closures) =====
import LeanCode.FreeEnergy.ContactError
import LeanCode.FreeEnergy.Convergence
import LeanCode.FreeEnergy.InnerIntegral
import LeanCode.FreeEnergy.LJIntegral
import LeanCode.FreeEnergy.OuterIntegral
import LeanCode.FreeEnergy.SumRule
import LeanCode.Closures.ClosureExpansions
import LeanCode.Closures.DPClosureMap
import LeanCode.Closures.FirstOrderEquivalence
import LeanCode.Closures.MSASolutionFamily

-- The FMSA-DP paper's scope and axiom gate.  Imported last, and deliberately:
-- it contains no mathematics, only #guard_msgs blocks asserting the axiom set of
-- each result the paper cites.  `lake build` therefore FAILS if the paper's
-- central verification claim stops being true, instead of that being discovered
-- by re-auditing the ledger by hand.
--
-- If a guard here fails, the fix is normally the PAPER, not the guard.
import LeanCode.FMSAProject
