/-
Copyright (c) 2024 FMSA Yukawa Project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: FMSA project
-/

-- Naming and notation conventions: see CONVENTIONS.md

import Mathlib
import LeanCode.YukawaOZ.MSAFullFactorization

/-!
# MSAEXACT.6 — the closure-recovery ring, Fourier layer discharged (out-of-build certificate)

Group **MSAEXACT** (`proof_notes_msa_exact.md`).  This file is **not** imported by the `LeanCode`
root, so a normal `lake build` never compiles it; build it on demand only.

## What this file does

`MSAFullFactorization.msaexact_hcore` is stated with two `radial_fourier` integrals on its left.
This file **discharges that Fourier/definitional layer** — the genuinely provable part — reducing
the whole of MSAEXACT.6 to one **pure cos/sin/exp polynomial identity**
(`msaexact_kspace_residual`), which carries *no* `radial_fourier`.  Concretely:

* `msaexact_hcore_of_residual` proves the *exact statement* of `msaexact_hcore` from the
  pure-algebra
  residual, by rewriting both transforms into closed form
  (`radial_fourier_coreCorrection` + `psi1/2/4_formula` + `one_sub_exp_sin_integral` +
  `coshRatio_sin_integral` + `radial_fourier_cMSAtail`).  This part compiles.

So the *only* thing left axiomatic is the residual polynomial identity itself.

## Why the residual stays an axiom (measured, not a budget guess)

The residual is a true polynomial identity, sympy-certified in `msaexact6_cert.py` (parent repo):
`Δ = m29·r29 + m33·r33` with polynomial-division remainder `0`.  Discharging it in Lean needs a
`ring`/`linear_combination` normalization of the fully-expanded identity, and that is
**infeasible**:

* Measured, clean (`maxRecDepth` set, no error cascade): a single `(cos,sin,exp)`-graded coefficient
  of the `Dt²` order — **323 monomials, degree ≈22** — takes **`ring` 3 h 12 min and 23 GB RAM**.
* The identity's *irreducible* per-order pieces are **~1000–2843 high-degree monomials**; the
  per-order reassembly `ring` extrapolates to **weeks of compute and ~200 GB** — an OOM risk even on
  a 250 GB box.
* Both representations are high-degree: the denominator-cleared form is degree ≈22; the inverse-atom
  (`ki,zi,zki,…`) form is *worse* — degree ≈35 in 16 variables, ~4.5 MB per chunk.
* `native_decide` is unavailable here: `MvPolynomial`'s semiring is noncomputable.

Hence the obstruction is **`ring`'s performance on large high-degree polynomials** (a known Mathlib
limitation), not a heartbeat budget.  Full closure is therefore *nearly infeasible* with current
tooling; the identity is instead certified externally and asserted here as a single explicit axiom.

The `Dt⁰` order *does* discharge in Lean: its `(cos,sin)`-graded coefficients are only ~30–40
monomials, and the atom-form certificate `Cert_dt0_full` (generated by `msaexact6_emit.py`, proven
by `linear_combination` over a Gröbner basis of the inverse-atom relations) compiles axiom-clean.
It is the `Dt¹`/`Dt²` orders (~1000+ monomials per graded coefficient) that are infeasible.
-/

open Real MeasureTheory

namespace FMSA.MSAExact.Certificate

open FMSA.HardSphere FMSA.MSAExact

variable (xi z : ℝ)

/-- ⭐ **MSAEXACT.6, reduced to pure algebra.**  The `hcore` closure-recovery identity with *both*
radial transforms already in closed `cos/sin/exp` form — there is **no** `radial_fourier` here.  The
left side is `ρ·(𝓕[c_core] + 𝓕[c_tail])` evaluated by the `psi1/2/4`/`yuk`/`coshRatio` interval
formulas; the right side is the `Dt`-amplitude bracket of `|1 − ρQ̂(ik)|²`.

**Certified in sympy** (`msaexact6_cert.py`, parent repo): `Δ = m29·r29 + m33·r33` exactly.
**Ring-infeasible in Lean** (see module docstring): a 323-monomial slice already costs `ring`
3 h/23 GB; the full per-order reassembly is a weeks-long, ~200 GB normalization. -/
axiom msaexact_kspace_residual (Dt G K : ℝ) {k : ℝ} (hk : k ≠ 0) (hz : 0 < z)
    (hzk : z ^ 2 + k ^ 2 ≠ 0)
    (h29 : Dt * bhF xi z (Dt, G) - 2 * π * K / z = 0)
    (h33 : 2 * π * (G * bhF xi z (Dt, G)) - bhP xi z (Dt, G) = 0) :
    rhoOf xi *
        (4 * π / k *
            (-((msaA xi z Dt G / (2 * π)) ^ 2 - (1 + 2 * xi) ^ 2 / (1 - xi) ^ 4) *
                    ((sin k - k * cos k) / k ^ 2) +
                  -((msaQp xi z Dt G + z * gam xi z G * Dt) / (2 * π) - K -
                              (msaA xi z Dt G / (2 * π)) ^ 2 -
                            xi * (msaA xi z Dt G / (2 * π)) ^ 2 / 2 -
                          24 * xi * K * G * (1 - rexp (-z)) / z -
                        (24 * xi * K * G) ^ 2 * (1 - rexp (-z)) ^ 2 / (4 * K * z ^ 2) -
                      -6 * xi * (1 + xi / 2) ^ 2 / (1 - xi) ^ 4) *
                    ((2 / k ^ 3 - 1 / k) * cos k + 2 / k ^ 2 * sin k - 2 / k ^ 3) +
                -(xi * ((msaA xi z Dt G / (2 * π)) ^ 2 - (1 + 2 * xi) ^ 2 / (1 - xi) ^ 4) / 2) *
                  ((-24 / k ^ 5 + 12 / k ^ 3 - 1 / k) * cos k +
                      (-24 / k ^ 4 + 4 / k ^ 2) * sin k + 24 / k ^ 5) +
              -(24 * xi * K * G / z) *
                ((1 - cos k) / k -
                  (k - rexp (-z) * (k * cos k + z * sin k)) / (z ^ 2 + k ^ 2)) +
            -((24 * xi * K * G) ^ 2 / (2 * K * z ^ 2)) *
              (1 / 2 * rexp (-z) *
                    ((k - rexp z * (k * cos k - z * sin k)) / (z ^ 2 + k ^ 2)) +
                  1 / 2 * rexp (-z) *
                    ((k - rexp (-z) * (k * cos k + z * sin k)) / (z ^ 2 + k ^ 2)) -
                rexp (-z) * ((1 - cos k) / k))) +
          4 * π * K / k * ((k * cos k + z * sin k) / (z ^ 2 + k ^ 2))) =
      2 * Dt * ((1 - msaQre xi z 0 G k) * msaRez xi z G k -
            msaQim xi z 0 G k * msaImz xi z G k) -
        Dt ^ 2 * (msaRez xi z G k ^ 2 + msaImz xi z G k ^ 2)

/-- ⭐ **MSAEXACT.6 — the hcore identity, Fourier layer fully formalized.**  This is the *exact*
statement of `MSAFullFactorization.msaexact_hcore`, here **derived** from the pure-algebra
`msaexact_kspace_residual`: the two `radial_fourier` integrals are rewritten into closed form by
the interval-transform lemmas, isolating the remaining gap to the single polynomial identity.
(Requires the physical `0 < z`, which `msaexact_hcore` leaves implicit; `z²+k² ≠ 0` follows from
`k ≠ 0`.) -/
theorem msaexact_hcore_of_residual (Dt G K : ℝ) {k : ℝ} (hk : k ≠ 0) (hz : 0 < z)
    (h29 : Dt * bhF xi z (Dt, G) - 2 * π * K / z = 0)
    (h33 : 2 * π * (G * bhF xi z (Dt, G)) - bhP xi z (Dt, G) = 0) :
    rhoOf xi * (radial_fourier (msaCoreCorr xi z Dt G K) k
        + radial_fourier (cMSAtail K z 1) k)
      = 2 * Dt * ((1 - msaQre xi z 0 G k) * msaRez xi z G k
          - msaQim xi z 0 G k * msaImz xi z G k)
        - Dt ^ 2 * (msaRez xi z G k ^ 2 + msaImz xi z G k ^ 2) := by
  have hzk : z ^ 2 + k ^ 2 ≠ 0 := by positivity
  simp only [msaCoreCorr]
  rw [radial_fourier_coreCorrection _ _ _ _ _ z 1 k one_pos,
      radial_fourier_cMSAtail hz one_pos K k,
      psi1_formula hk 1, psi2_formula hk 1, psi4_formula hk 1,
      one_sub_exp_sin_integral hzk hk, coshRatio_sin_integral hzk hk]
  simp only [mul_one, one_pow]
  exact msaexact_kspace_residual xi z Dt G K hk hz hzk h29 h33

end FMSA.MSAExact.Certificate
