/-
Copyright (c) 2024 FMSA Yukawa Project contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: FMSA project
-/

-- Naming and notation conventions: see CONVENTIONS.md

import Mathlib
import LeanCode.HardSphere.OzBaxterFixedPt
import LeanCode.HardSphere.BaxterExteriorRegularityGeneral

/-!
# OZ layer: translating the Baxter exterior analysis into `ozBaxterFixedPt` form (`OZFIX.26`)

The mathematics of the exterior decay/boundedness/integrability results is entirely about
`baxterPsi`/`baxterPsiOuter`; the `ozBaxterFixedPt` phrasing is a **thin veneer**, generated by the
single translation `r · ozBaxterFixedPt r = baxterPsi r` (`r > 0`, `ozBaxterFixedPt_eq_div`).

This file is the **OZ layer**: it collects those wrappers so that the Baxter analysis files
(`BaxterDiluteDecay`, `BaxterExteriorDecayReduction`, `BaxterExteriorRegularityGeneral`) stay free of
any `oz*` dependency — the layering `Baxter (pure analysis) → OZ (interface)` rather than the
inverted one they had before.
-/

open MeasureTheory Set Filter Topology

namespace FMSA.HardSphere

noncomputable section

variable {eta sigma rho : ℝ}

/-- **Decay clause** of `baxter_exterior_regularity` (inside clause 6), dilute regime:
`r · ozBaxterFixedPt r → 0` (which is `baxterPsi r → 0` since `ozBaxterFixedPt = baxterPsi/·`). -/
theorem r_mul_ozBaxterFixedPt_tendsto_zero_of_dilute {eta sigma rho : ℝ} (hsigma : 0 < sigma)
    (hL1 : q0AbsL1 eta sigma rho < 1) :
    Tendsto (fun r => r * ozBaxterFixedPt eta sigma rho r) atTop (𝓝 0) := by
  have hdecay := baxterPsi_tendsto_zero_of_dilute hsigma hL1
  have heq : baxterPsiOuter eta sigma rho =ᶠ[atTop]
      (fun r => r * ozBaxterFixedPt eta sigma rho r) := by
    filter_upwards [eventually_ge_atTop sigma] with r hr
    have hr0 : 0 < r := lt_of_lt_of_le hsigma hr
    rw [ozBaxterFixedPt_eq_div hsigma hr0, baxterPsi_outer hr]
    field_simp
  exact hdecay.congr' heq

/-- Dilute decay clause, physically parametrised (`η < (3−√7)/2`). -/
theorem r_mul_ozBaxterFixedPt_tendsto_zero_of_eta_dilute {eta sigma rho : ℝ} (heta0 : 0 < eta)
    (heta1 : eta < 1) (hsigma : 0 < sigma) (hrho : 0 ≤ rho)
    (heta_def : eta = Real.pi * rho * sigma ^ 3 / 6) (hdilute : eta < (3 - Real.sqrt 7) / 2) :
    Tendsto (fun r => r * ozBaxterFixedPt eta sigma rho r) atTop (𝓝 0) :=
  r_mul_ozBaxterFixedPt_tendsto_zero_of_dilute hsigma
    (q0AbsL1_lt_one_of_dilute heta0 heta1 hsigma hrho heta_def hdilute)

/-- **Decay clause from decay.**  `Tendsto (r·ozBaxterFixedPt r) atTop 0`, since for `r ≥ σ`,
`r·ozBaxterFixedPt r = baxterPsi r = baxterPsiOuter r` and the latter `→ 0`. -/
theorem r_mul_ozBaxterFixedPt_tendsto_zero_of_tendsto_zero {eta sigma rho : ℝ} (hsigma : 0 < sigma)
    (hdecay : Tendsto (baxterPsiOuter eta sigma rho) atTop (𝓝 0)) :
    Tendsto (fun r => r * ozBaxterFixedPt eta sigma rho r) atTop (𝓝 0) := by
  have heq : baxterPsiOuter eta sigma rho =ᶠ[atTop]
      (fun r => r * ozBaxterFixedPt eta sigma rho r) := by
    filter_upwards [eventually_ge_atTop sigma] with r hr
    have hr0 : 0 < r := lt_of_lt_of_le hsigma hr
    rw [ozBaxterFixedPt_eq_div hsigma hr0, baxterPsi_outer hr]
    field_simp
  exact hdecay.congr' heq

/-- **Exterior decay clause of `baxter_exterior_regularity`, all physical `η < 1`.** -/
theorem r_mul_ozBaxterFixedPt_tendsto_zero (heta0 : 0 < eta) (heta1 : eta < 1) (hsigma : 0 < sigma)
    (hrho : 0 < rho) (heta_def : eta = Real.pi * rho * sigma ^ 3 / 6) :
    Tendsto (fun r => r * ozBaxterFixedPt eta sigma rho r) atTop (𝓝 0) :=
  r_mul_ozBaxterFixedPt_tendsto_zero_of_tendsto_zero hsigma
    (baxterPsiOuter_tendsto_zero heta0 heta1 hsigma hrho heta_def)

/-- **Integrability clause `IntegrableOn (r·ozBaxterFixedPt) (Ioi σ)` of
`baxter_exterior_regularity` (clause 6c), all physical `η < 1`.**  On `(σ,∞)`,
`r·ozBaxterFixedPt r = baxterPsi r = baxterPsiOuter r`. -/
theorem r_mul_ozBaxterFixedPt_integrableOn (heta0 : 0 < eta) (heta1 : eta < 1) (hsigma : 0 < sigma)
    (hrho : 0 < rho) (heta_def : eta = Real.pi * rho * sigma ^ 3 / 6) :
    IntegrableOn (fun r => r * ozBaxterFixedPt eta sigma rho r) (Ioi sigma) := by
  refine (baxterPsiOuter_integrableOn heta0 heta1 hsigma hrho heta_def).congr_fun
    ?_ measurableSet_Ioi
  intro r hr
  have hr0 : 0 < r := lt_trans hsigma (mem_Ioi.mp hr)
  have hrσ : sigma ≤ r := le_of_lt (mem_Ioi.mp hr)
  change baxterPsiOuter eta sigma rho r = r * ozBaxterFixedPt eta sigma rho r
  rw [ozBaxterFixedPt_eq_div hsigma hr0, baxterPsi_outer hrσ]
  field_simp

end

end FMSA.HardSphere
